In [1]:
import numpy as np

In [3]:
np.array([1,2,3,4]) #array함수에 리스트를 넣음, 1차원 배열
print(type(np.array([1,2,3,4]))) # <class 'numpy.ndarray'>

#파이썬 연산
ans=[]
data=[1,2,3,4]
for i in data:
    ans.append(i+1)
print(ans)

#넘파이 연산
print(np.array(data))
print(np.array(data)+1)
print(np.array(data)*3)


<class 'numpy.ndarray'>
[2, 3, 4, 5]
[1 2 3 4]
[2 3 4 5]
[ 3  6  9 12]


In [4]:
x=np.array([1,2,3])
y=np.array([4,5,6])


print(x*y) #요소간 곱셈
print(2*x+y)
print(x == y) #요소간 비교연산
print(x > 2)
print((x>2) & (y>4)) #and

[ 4 10 18]
[ 6  9 12]
[False False False]
[False False  True]
[False False  True]


In [5]:
#1차원 배열 : 벡터
#2차원 배열 : 행렬

#2*3배열
x=np.array([[1,2,3],[4,5,6]])

print(len(x)) #행의 개수
print(len(x[0])) #열의 개수

2
3


In [8]:
x=np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])
# x배열의 깊이 : 2
# x배열의 행 : 2
# x배열의 열 : 3
# x : 2*2*3 배열

print(x)
print(x.shape) # 3 차원 

[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]
(2, 2, 3)


In [ ]:
x=np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              [[11, 12, 13, 14],
               [15, 16, 17, 18],
               [19, 20, 21, 22]]])

# 3차원배열x = [행렬1, 행렬2]
# x[0]=행렬1
# x[1]=행렬2
# x[0][0]=행렬1의 첫번째 행

# x배열의 깊이 : 2
# x배열의 행 : 3
# x배열의 열 : 4
# x배열의 shape? 2*3*4 배열
print(len(x)) #깊이
print(len(x[0])) #행
print(len(x[0][0])) #열

In [9]:
print(x.ndim) #배열의 차원
print(x.shape)    #shape(배열의 크기)

3
(2, 2, 3)


In [10]:
x=np.array([1,2,3])

print(x[-1])

3


In [13]:
x=np.array([[1,2,3],
            [4,5,6]])

print(x)
print("")
print(x[0])#첫번째 행 출력
print(x[1])

print("")
print(x[-1]) #마지막 행으로부터 거꾸로 참조
print(x[-2])
print("")

print(x[0][0])#첫번째 행의 첫번째 열 출력
print(x[-2][0])
print(x[-2][-3])
print(x[0,0]) #컴마를 이용한 접근도 가능. 컴마로 구분된 차원을 축(axis)라고 함

print(x[-1][-1])

[[1 2 3]
 [4 5 6]]

[1 2 3]
[4 5 6]

[4 5 6]
[1 2 3]

1
1
1
1
6


In [15]:
x=np.array([[1,2,3],
            [4,5,6]])

print(x[0])        #첫번째 행 전체
print(x[0,])       #x[행,열], #첫번째 행 전체
print(x[0, : ])    ##첫번째 행 전체
print("")
print(x[1])
print(x[1, :])
print("")
print(x[:,1])   #x[행,열]

print("-"*50)
# array([5, 6])출력
print(x[1][1:])
print(x[1,1:])
print(x[1][1:3])
print(x[-1][-2:])

[1 2 3]
[1 2 3]
[1 2 3]

[4 5 6]
[4 5 6]

[2 5]
--------------------------------------------------
[5 6]
[5 6]
[5 6]
[5 6]


In [16]:
#불린참조, 불린값(True/False)으로 구성된 배열로 참조,
#주의:참조 대상 배열(x)과 불린 배열(b)의 크기가 동일

x=np.array([1,2,3])
b=np.array([True, False, True])

print(x[b]) #True 에 해당되는 자료가 추출

[1 3]


In [26]:
print(x>1)
print(x[x>1])


x=np.array([1,2,3])
#b=np.array([True, False, True, True])
#b=np.array([True, False, True])
print(x%2==1)
print(x[x%2==1])

[ True  True  True  True  True]
[10 20 30 40 50]
[ True False  True]
[1 3]


In [28]:
x=np.array([10,20,30,40,50])
#y=np.array([0,2,4])
y=np.array([0,2,4,0,0,2])

#정수 배열 인덱싱
print(x[y]) # 배열로 인덱싱 

[10 30 50 10 10 30]


In [30]:
x=np.array([[10,20,30]
            ,[40,50,60]])
print(x)
print("="*50)
# True 열 값 출력 
print(x[ : ,[True,False,True]]) #0번 2번 index 열 데이터 추출

print(x[[True,False],:])  #0번 index 행 데이터 추출
print(""*50)

# 전체 
print(x[:])

[[10 20 30]
 [40 50 60]]
[[10 30]
 [40 60]]
[[10 20 30]]

[[10 20 30]
 [40 50 60]]


In [33]:
print(x[ : , [0,2]])
print(x[ : , [2,0]])
print("="*50)
print(x[ : , [2,0,0,2,0]])

print("="*50)
print(x[[1,1,1,0],:])
print("="*50)
print(x[[1,0],:])

[[10 30]
 [40 60]]
[[30 10]
 [60 40]]
[[30 10 10 30 10]
 [60 40 40 60 40]]
[[40 50 60]
 [40 50 60]
 [40 50 60]
 [10 20 30]]
[[40 50 60]
 [10 20 30]]


In [35]:
x= np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])

print(x)
# 7참조
print("="*50)
print(x[1 ,2])
print(x[x==7]) # 조건 
# 14참조
print("="*50)
print(x[-1, -1]) # 뒤에서 참조
# [6,7]참조
print("="*50)
print(x[1,1:3])
print(x[1,[1, 2]])
print(x[(x==6)|(x==7)]) # or 조건 

# [7,12]참조
print("="*50)
print(x[1:,2])
print(x[1:3,2])
# [[3,4],[8,9]]
print("="*50)
print(x[0:2,3:5]) # 범위 
print("="*50)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
7
[7]
14
[6 7]
[6 7]
[6 7]
[ 7 12]
[ 7 12]
[[3 4]
 [8 9]]


In [36]:
# 조건 참조
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

# 3의 배수 출력
# 4로 나누었을때 나머지가 1인 값을 출력
# 3으로 나누어지고 4로 나누면 나머지가 1인 값을 출력
print(x[x%3==0])
print(x[x%4==1])
print(x[(x%3==0) & (x%4==1)])


[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[9]


In [37]:
x=np.array([1, 2.5])

print(type(x))

#배열에 저장된 자료 타입 확인
print(x.dtype)

<class 'numpy.ndarray'>
float64


In [38]:
x=np.array([1, 2.5], dtype='i') #dtype:f
print(x.dtype)
print(x)

int32
[1 2]


In [39]:
print(np.inf) #무한대를 표현하는 상수
print(np.nan) #정의할 수 없는 숫자 

inf
nan


In [41]:
print(np.array([1]) / np.array([0])) #inf
print(np.array([0]) / np.array([1])) #0
print(np.array([-1]) / np.array([0]))
print(np.array([0]) / np.array([0]))
print(np.log(0))
print("="*50)
print(np.exp(-np.inf))
print("="*50)


print(np.zeros(3))

[inf]
[0.]
[-inf]
[nan]
-inf
0.0
[0. 0. 0.]


<ipython-input-41-d5b2c7190164>:1: RuntimeWarning: divide by zero encountered in true_divide
  print(np.array([1]) / np.array([0])) #inf
<ipython-input-41-d5b2c7190164>:3: RuntimeWarning: divide by zero encountered in true_divide
  print(np.array([-1]) / np.array([0]))
<ipython-input-41-d5b2c7190164>:4: RuntimeWarning: invalid value encountered in true_divide
  print(np.array([0]) / np.array([0]))
<ipython-input-41-d5b2c7190164>:5: RuntimeWarning: divide by zero encountered in log
  print(np.log(0))


In [45]:
# 값이 0 인 배열 생성 하기 
print(np.zeros((3,2)))
print("="*50)
print(np.zeros((3,2,4))) #(깊이,행,열)
print("="*50)

print(np.zeros((3,2,4), dtype='i'))
print(np.zeros((3,2,4), dtype='i').dtype)

# 값이 1인 배열
print("="*50)
print(np.ones((2,3,4)))

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[[[0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]]]


dtype('int32')

In [48]:
x=np.zeros(5, dtype='U4')

x[0]="test"
print(x.dtype)
print(x)
x

<U4
['test' '' '' '' '']


array(['test', '', '', '', ''], dtype='<U4')

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [52]:
# 테스트 코드 작성시 유용하게 쓰일것 같음 별 다섯개
x=np.ones((2,3,4))
print(x)
print("=" * 50)
y=np.ones_like(x, dtype='i')
# zeros(ones)_like함수 : x배열의 크기와 동일하게 0 또는 1로 모두 초기화하여 생성
y

# np.ones_like(x, dtype='i') 작업을 하면 컴퓨터 내부에서는 어떤 일이?
# x배열 크기 확인 -> x배열 크기와 동일한 배열 공간 생성 -> 1로 모두 초기화

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [53]:
np.empty((3,2)) 
#zeros:0으로 초기화, empty:기존에 메모리에 남아있는 쓰레기값으로 초기화

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [58]:
print(np.array(list(range(8))))
print("="*50)
print(np.array(list(range(8))).reshape(4,2))

print("="*50)
print(np.arange(8)) #np.array(list(range(8)))
print(np.arange(8).reshape(2,4))
print("="*50)

[0 1 2 3 4 5 6 7]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[0 1 2 3 4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]


In [59]:
print(np.arange(1,11) )
print(np.arange(1,11,2) )



[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [60]:
np.linspace(0, 100, 10) #선형 구간, 시작, 끝, 개수

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [61]:
# 테스트 할때 유용 별 5개 (예제 코드 작성시)
#np.logspace(시작, 끝, 개수, base)#로그 스케일 값으로 배열 생성

print(np.logspace(start=1,stop=10,num=10)) #base가 생략(기본값 10)
print(np.logspace(start=1,stop=10,num=10, base=10))
print("="*50)
print(np.logspace(start=1,stop=10,num=10, base=2))  #base가 2

[1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09 1.e+10]
[1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09 1.e+10]
[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]


In [62]:
#전치행렬:행과열을 바꾸어놓은 행렬, T속성을 이용
#1~6까지 2행3열 행렬생성
X=np.arange(1,7).reshape((2,3))
X.T


array([[1, 4],
       [2, 5],
       [3, 6]])

In [65]:
#엘리먼트 와이즈 프로덕
#element wise product : 요소간 곱셈 연산

#닷 프로덕, 매트릭스 멀티플라이(행렬의 곱셈)
#dot product, matrix multiply

x=np.arange(12)
print(x.reshape(3,4))
print("="* 50)


x=np.arange(12)
print(x.reshape(3,-1)) # arange(12에 대한 행은 3행)
print("="* 50)
print(x.reshape(4, -1)) # arange(12에 대한 행은 4행)
print("="* 50)
print(x.reshape(-1, 2)) #열은 2개, 행은 네가 계산해서 알아서 해
print("="* 50)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [67]:
x=np.arange(24)
print(x)
print("="* 50)
print(x.reshape(2,3,-1)) # 깊이 2, 3행
print("="* 50)
print(x.reshape(2,-1, 3)) # 깊이 2, ,3열 
print("="* 50)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [69]:
#reshape으로 차원을 증가시킬 수 있다
#ex) reshape함수 : 1차원 배열 -> 다차원 배열

#ex) flatten 또는 ravel함수 : 다차원 배열 -> 1차원 배열

x=x.reshape(2,3,-1)
print(x.shape)
print(x.ndim)
x

(2, 3, 4)
3


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [70]:
x.flatten() # 다차원 => 1차원

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [71]:
x.ravel() # 다차원 => 1차원 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [73]:
# 판다스 
import pandas as pd
df=pd.read_csv("samsung.csv")
df

Open   High    Low  Close    Adj Close    Volume
0    57000  58800  56400  58600  56560.60547  48431566
1    60300  60400  58600  59000  56946.68750  36476611
2    59700  60100  59000  59000  56946.68750  19285354
3    59500  59600  57700  57900  55884.96875  21943345
4    57800  57900  56700  56800  54823.25000  21158940
..     ...    ...    ...    ...          ...       ...
244  79000  79800  78900  79700  79700.00000  12618790
245  79700  79900  79200  79300  79300.00000   9098910
246  79400  79500  78800  78800  78800.00000  10040975
247  79200  79400  78500  78500  78500.00000  11427693
248  78300  78900  78100  78300  78300.00000  10204299

[249 rows x 6 columns]

In [74]:
samsung=np.loadtxt("samsung.csv", skiprows=1, delimiter=',') # skiprows 옵션 첫번째 줄 스킵
print(samsung.shape) # 249행 6열 
samsung
#samsung 변수에 담긴 배열을 이용하여 오늘 학습한 함수, 열, 행 추출


(249, 6)


array([[   57000.     ,    58800.     ,    56400.     ,    58600.     ,
           56560.60547, 48431566.     ],
       [   60300.     ,    60400.     ,    58600.     ,    59000.     ,
           56946.6875 , 36476611.     ],
       [   59700.     ,    60100.     ,    59000.     ,    59000.     ,
           56946.6875 , 19285354.     ],
       ...,
       [   79400.     ,    79500.     ,    78800.     ,    78800.     ,
           78800.     , 10040975.     ],
       [   79200.     ,    79400.     ,    78500.     ,    78500.     ,
           78500.     , 11427693.     ],
       [   78300.     ,    78900.     ,    78100.     ,    78300.     ,
           78300.     , 10204299.     ]])

In [78]:
df=pd.read_csv("train.csv")
print(df['Name'])
print("="* 50)
print(df['Name'][0])
print("="* 50)
print(df['Name'][1])
print("="* 50)
print(df['Name'][890])
print("="* 50)

print(len(df['Name']))
print(df['Name'][0])

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...                        
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object
Braund, Mr. Owen Harris
Cumings, Mrs. John Bradley (Florence Briggs Thayer)
Dooley, Mr. Patrick
891
Braund, Mr. Owen Harris
