In [1]:
#표준화 : 평균 0, 표준편차 1인 표준정규분포
# 1)표준화=(각데이터-평균값)/표준편차
# 2)zscore()
# 3)fit_transform()

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot
import seaborn as sns

In [7]:
data=np.random.randint(30, size=(6,5))
data

array([[ 4, 10,  3, 25, 27],
       [ 7, 23, 18, 27,  6],
       [25,  4, 17, 12,  1],
       [23, 17, 15,  4, 15],
       [21,  5, 14,  1, 17],
       [11, 28, 23, 11, 18]])

In [17]:
#6행5열, 각 열 단위로 표준화 작업을 진행하고 출력
#표준화=(각데이터-평균값)/표준편차

data_s1=(data - np.mean(data,axis=0)) / np.std(data,axis=0)

In [11]:
# data.mean() #전체 평균
# np.mean(data) #전체 평균

# np.mean(data,axis=0) #5개, 열 기준 평균
# np.mean(data,axis=1) #6개, 행 기준 평균

array([13.8, 16.2, 11.8, 14.8, 11.6, 18.2])

In [13]:
# data.mean(axis=0)#5개, 열 기준 평균
# data.mean(axis=1) #6개, 행 기준 평균

array([13.8, 16.2, 11.8, 14.8, 11.6, 18.2])

In [18]:
import scipy.stats as ss

In [21]:
data_s1

array([[-1.36620938, -0.50233101, -1.97278785,  1.19767534,  1.53920722],
       [-0.99916805,  0.94884747,  0.49319696,  1.40299112, -0.94720445],
       [ 1.2030799 , -1.1721057 ,  0.32879797, -0.13687718, -1.53920722],
       [ 0.95838568,  0.27907279,  0.        , -0.95814028,  0.11840056],
       [ 0.71369147, -1.06047659, -0.16439899, -1.26611394,  0.35520167],
       [-0.50977962,  1.50699304,  1.3151919 , -0.23953507,  0.47360222]])

In [20]:
data_s2=ss.zscore(data)
data_s2

array([[-1.36620938, -0.50233101, -1.97278785,  1.19767534,  1.53920722],
       [-0.99916805,  0.94884747,  0.49319696,  1.40299112, -0.94720445],
       [ 1.2030799 , -1.1721057 ,  0.32879797, -0.13687718, -1.53920722],
       [ 0.95838568,  0.27907279,  0.        , -0.95814028,  0.11840056],
       [ 0.71369147, -1.06047659, -0.16439899, -1.26611394,  0.35520167],
       [-0.50977962,  1.50699304,  1.3151919 , -0.23953507,  0.47360222]])

In [22]:
from sklearn.preprocessing import StandardScaler

In [24]:
data_s3=StandardScaler().fit_transform(data)
data_s3

array([[-1.36620938, -0.50233101, -1.97278785,  1.19767534,  1.53920722],
       [-0.99916805,  0.94884747,  0.49319696,  1.40299112, -0.94720445],
       [ 1.2030799 , -1.1721057 ,  0.32879797, -0.13687718, -1.53920722],
       [ 0.95838568,  0.27907279,  0.        , -0.95814028,  0.11840056],
       [ 0.71369147, -1.06047659, -0.16439899, -1.26611394,  0.35520167],
       [-0.50977962,  1.50699304,  1.3151919 , -0.23953507,  0.47360222]])

In [26]:
#평균보다 이상치에 덜 민감한 중앙값을 사용

from sklearn.preprocessing import RobustScaler
#RobustScaler는 기존의 표준화방법의 문제점인 평균, 표준편차는
#특이값의 영향을 많이 받게됨 -> 표준화 결과가 왜곡

#RobustScaler로 표준화 = (각데이터-중앙값)/IQR

In [27]:
RobustScaler().fit_transform(data)

array([[-0.82758621, -0.2295082 , -3.71428571,  0.84375   ,  1.15789474],
       [-0.62068966,  0.62295082,  0.57142857,  0.96875   , -1.05263158],
       [ 0.62068966, -0.62295082,  0.28571429,  0.03125   , -1.57894737],
       [ 0.48275862,  0.2295082 , -0.28571429, -0.46875   , -0.10526316],
       [ 0.34482759, -0.55737705, -0.57142857, -0.65625   ,  0.10526316],
       [-0.34482759,  0.95081967,  2.        , -0.03125   ,  0.21052632]])

In [28]:
from sklearn.preprocessing import MinMaxScaler, minmax_scale

In [29]:
#MinMaxScaler, minmax_scale:0~1사이의 값으로 스케일링

In [30]:
data

array([[ 4, 10,  3, 25, 27],
       [ 7, 23, 18, 27,  6],
       [25,  4, 17, 12,  1],
       [23, 17, 15,  4, 15],
       [21,  5, 14,  1, 17],
       [11, 28, 23, 11, 18]])

In [38]:
data_m1=(data-data.min(axis=0)) / (data.max(axis=0)-data.min(axis=0))
data_m1

array([[0.        , 0.25      , 0.        , 0.92307692, 1.        ],
       [0.14285714, 0.79166667, 0.75      , 1.        , 0.19230769],
       [1.        , 0.        , 0.7       , 0.42307692, 0.        ],
       [0.9047619 , 0.54166667, 0.6       , 0.11538462, 0.53846154],
       [0.80952381, 0.04166667, 0.55      , 0.        , 0.61538462],
       [0.33333333, 1.        , 1.        , 0.38461538, 0.65384615]])

In [39]:
data_m2=MinMaxScaler().fit_transform(data)
data_m2

array([[0.        , 0.25      , 0.        , 0.92307692, 1.        ],
       [0.14285714, 0.79166667, 0.75      , 1.        , 0.19230769],
       [1.        , 0.        , 0.7       , 0.42307692, 0.        ],
       [0.9047619 , 0.54166667, 0.6       , 0.11538462, 0.53846154],
       [0.80952381, 0.04166667, 0.55      , 0.        , 0.61538462],
       [0.33333333, 1.        , 1.        , 0.38461538, 0.65384615]])

In [40]:
minmax_scale(data, axis=0)

array([[0.        , 0.25      , 0.        , 0.92307692, 1.        ],
       [0.14285714, 0.79166667, 0.75      , 1.        , 0.19230769],
       [1.        , 0.        , 0.7       , 0.42307692, 0.        ],
       [0.9047619 , 0.54166667, 0.6       , 0.11538462, 0.53846154],
       [0.80952381, 0.04166667, 0.55      , 0.        , 0.61538462],
       [0.33333333, 1.        , 1.        , 0.38461538, 0.65384615]])

In [41]:
#이진화
#연속형 변수값 -> 기준에 따라 -> 0또는 1로 이진화
#베르누이 시행(성공/실패)
#성공확률이 p인 베르누이 시행을  n번 반복했을때, 
#성공횟수를 x라고 한다면, 
#확률변수 x는 n과 p인 이항분포를 따른다

In [42]:
data

array([[ 4, 10,  3, 25, 27],
       [ 7, 23, 18, 27,  6],
       [25,  4, 17, 12,  1],
       [23, 17, 15,  4, 15],
       [21,  5, 14,  1, 17],
       [11, 28, 23, 11, 18]])

In [43]:
#이산화(이항변수화)
from sklearn.preprocessing import Binarizer

In [49]:
binarizer=Binarizer().fit(data)
binarizer.transform(data)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [46]:
print(binarizer)

Binarizer()


In [48]:
help(Binarizer())

Help on Binarizer in module sklearn.preprocessing._data object:

class Binarizer(sklearn.base.TransformerMixin, sklearn.base.BaseEstimator)
 |  Binarizer(*, threshold=0.0, copy=True)
 |  
 |  Binarize data (set feature values to 0 or 1) according to a threshold.
 |  
 |  Values greater than the threshold map to 1, while values less than
 |  or equal to the threshold map to 0. With the default threshold of 0,
 |  only positive values map to 1.
 |  
 |  Binarization is a common operation on text count data where the
 |  analyst can decide to only consider the presence or absence of a
 |  feature rather than a quantified number of occurrences for instance.
 |  
 |  It can also be used as a pre-processing step for estimators that
 |  consider boolean random variables (e.g. modelled using the Bernoulli
 |  distribution in a Bayesian setting).
 |  
 |  Read more in the :ref:`User Guide <preprocessing_binarization>`.
 |  
 |  Parameters
 |  ----------
 |  threshold : float, default=0.0
 |    

In [52]:
b2=Binarizer(threshold=15)
b2.transform(data)

array([[0, 0, 0, 1, 1],
       [0, 1, 1, 1, 0],
       [1, 0, 1, 0, 0],
       [1, 1, 0, 0, 0],
       [1, 0, 0, 0, 1],
       [0, 1, 1, 0, 1]])

In [53]:
from sklearn.preprocessing import binarize

In [55]:
#binarize(data)
binarize(data, threshold=15)

array([[0, 0, 0, 1, 1],
       [0, 1, 1, 1, 0],
       [1, 0, 1, 0, 0],
       [1, 1, 0, 0, 0],
       [1, 0, 0, 0, 1],
       [0, 1, 1, 0, 1]])

In [57]:
binarize(data, threshold=15, copy=False) #원본이 변경됨

array([[0, 0, 0, 1, 1],
       [0, 1, 1, 1, 0],
       [1, 0, 1, 0, 0],
       [1, 1, 0, 0, 0],
       [1, 0, 0, 0, 1],
       [0, 1, 1, 0, 1]])

In [58]:
data

array([[0, 0, 0, 1, 1],
       [0, 1, 1, 1, 0],
       [1, 0, 1, 0, 0],
       [1, 1, 0, 0, 0],
       [1, 0, 0, 0, 1],
       [0, 1, 1, 0, 1]])

In [ ]:
OneHotEncoder
#Hot은 1을 의미함. 1개만 1이고 나머지는 0이 되도록 인코딩
#범주형 -> 이산화
# ex) 성별(범주형) -> 0(남성) 또는 1(여성) -> 10 또는 01
# 연령대 -> 0(20대), 1(30대), 2(40대) -> 100 또는 010 또는 001
# 학점 ->  A(0),B(1),C(2),D(3),F(4) -> 10000 01000 00100 00010 00001


In [ ]:
#학생1  0 0 0    -> 원핫인코딩 -> 10 100 10000
#학생2  0 1 1
...
#학생n  1 1 4   -> 원핫인코딩 -> 01 010 00001

In [59]:
from sklearn.preprocessing import OneHotEncoder

In [61]:
data=np.array([[0,0,0],
         [0,1,1],
         [1,2,2],
         [1,2,4]])

In [62]:
#data->원핫인코딩

array([[0, 0, 0],
       [0, 1, 1],
       [1, 2, 2],
       [1, 2, 4]])

In [72]:
enc=OneHotEncoder()
enc.fit(data)

OneHotEncoder()

In [77]:
#enc.get_params()
#enc.get_feature_names()

In [76]:
enc.transform(data).toarray()

array([[1., 0., 1., 0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 1., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 1., 0., 0., 1., 0.],
       [0., 1., 0., 0., 1., 0., 0., 0., 1.]])

In [78]:
# array([[0, 0, 0],
#        [0, 1, 1],
#        [1, 2, 2],
#        [1, 2, 4]])

In [80]:
df = pd.DataFrame({'C1': np.random.randn(20),
 'C2': ['a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a','b', 'b', 'b', 'b', 'b', 'b', 'b', 'b', 'b', 'b']})

In [81]:
df

C1 C2
0   0.490417  a
1   0.304764  a
2  -0.925569  a
3   0.049322  a
4   0.883035  a
5  -0.880704  a
6  -0.676126  a
7  -2.165110  a
8   1.256704  a
9  -0.735027  a
10 -1.829067  b
11  1.649436  b
12  0.748258  b
13 -0.401665  b
14  0.237367  b
15  0.365278  b
16 -1.440535  b
17 -1.469205  b
18  0.441842  b
19 -0.940058  b

In [ ]:
# C1열 값에 대해 구간을 나누고자 함
# 최소값~최대값을 5개 구간으로 균등하게 나눔

In [85]:
#C1열 값에 대해 최소/최대값 출력
df.C1.min() # -2.165110427137061
df.C1.max() # 1.649436313331068

1.649436313331068

In [86]:
bins=np.linspace(df.C1.min(), df.C1.max(), 5) #균등구간
bins


array([-2.16511043, -1.21147374, -0.25783706,  0.69579963,  1.64943631])

In [88]:
df['C1bin']=np.digitize(df['C1'], bins)

In [90]:
#1 : -2.16511043 ~ -1.21147374 사이에 속함
df

C1 C2  C1bin
0   0.490417  a      3
1   0.304764  a      3
2  -0.925569  a      2
3   0.049322  a      3
4   0.883035  a      4
5  -0.880704  a      2
6  -0.676126  a      2
7  -2.165110  a      1
8   1.256704  a      4
9  -0.735027  a      2
10 -1.829067  b      1
11  1.649436  b      5
12  0.748258  b      4
13 -0.401665  b      2
14  0.237367  b      3
15  0.365278  b      3
16 -1.440535  b      1
17 -1.469205  b      1
18  0.441842  b      3
19 -0.940058  b      2

In [103]:
#각 구간별 데이터 건수 출력
df.groupby('C1bin').get_group(1)
df.groupby('C1bin').get_group(2)
#df.groupby('C1bin').ngroup()

df.groupby('C1bin')['C2'].value_counts()

C1bin  C2
1      b     3
       a     1
2      a     4
       b     2
3      a     3
       b     3
4      a     2
       b     1
5      b     1
Name: C2, dtype: int64

In [104]:
df['C1bin'].value_counts()


2    6
3    6
1    4
4    3
5    1
Name: C1bin, dtype: int64

In [105]:
df.groupby("C1bin").size()


C1bin
1    4
2    6
3    6
4    3
5    1
dtype: int64

In [109]:
df.groupby("C1bin")['C1'].std()
df.groupby("C1bin")['C1'].sum()
df.groupby("C1bin")['C1'].mean()

C1bin
1   -1.725979
2   -0.759858
3    0.314832
4    0.962665
5    1.649436
Name: C1, dtype: float64

In [112]:
df[df['C1bin']==2]

C1 C2  C1bin
2  -0.925569  a      2
5  -0.880704  a      2
6  -0.676126  a      2
9  -0.735027  a      2
13 -0.401665  b      2
19 -0.940058  b      2

In [113]:
df

C1 C2  C1bin
0   0.490417  a      3
1   0.304764  a      3
2  -0.925569  a      2
3   0.049322  a      3
4   0.883035  a      4
5  -0.880704  a      2
6  -0.676126  a      2
7  -2.165110  a      1
8   1.256704  a      4
9  -0.735027  a      2
10 -1.829067  b      1
11  1.649436  b      5
12  0.748258  b      4
13 -0.401665  b      2
14  0.237367  b      3
15  0.365278  b      3
16 -1.440535  b      1
17 -1.469205  b      1
18  0.441842  b      3
19 -0.940058  b      2

In [116]:
#df C1bin열에 대해
pd.get_dummies(df['C1bin'], prefix='C1')

C1_1  C1_2  C1_3  C1_4  C1_5
0      0     0     1     0     0
1      0     0     1     0     0
2      0     1     0     0     0
3      0     0     1     0     0
4      0     0     0     1     0
5      0     1     0     0     0
6      0     1     0     0     0
7      1     0     0     0     0
8      0     0     0     1     0
9      0     1     0     0     0
10     1     0     0     0     0
11     0     0     0     0     1
12     0     0     0     1     0
13     0     1     0     0     0
14     0     0     1     0     0
15     0     0     1     0     0
16     1     0     0     0     0
17     1     0     0     0     0
18     0     0     1     0     0
19     0     1     0     0     0

In [117]:
df
# c1열 값 > c1열 값의 평균 => 'high'
# else => 'low'
# high_low열에 저장

C1 C2  C1bin
0   0.490417  a      3
1   0.304764  a      3
2  -0.925569  a      2
3   0.049322  a      3
4   0.883035  a      4
5  -0.880704  a      2
6  -0.676126  a      2
7  -2.165110  a      1
8   1.256704  a      4
9  -0.735027  a      2
10 -1.829067  b      1
11  1.649436  b      5
12  0.748258  b      4
13 -0.401665  b      2
14  0.237367  b      3
15  0.365278  b      3
16 -1.440535  b      1
17 -1.469205  b      1
18  0.441842  b      3
19 -0.940058  b      2

In [118]:
df

C1 C2  C1bin
0   0.490417  a      3
1   0.304764  a      3
2  -0.925569  a      2
3   0.049322  a      3
4   0.883035  a      4
5  -0.880704  a      2
6  -0.676126  a      2
7  -2.165110  a      1
8   1.256704  a      4
9  -0.735027  a      2
10 -1.829067  b      1
11  1.649436  b      5
12  0.748258  b      4
13 -0.401665  b      2
14  0.237367  b      3
15  0.365278  b      3
16 -1.440535  b      1
17 -1.469205  b      1
18  0.441842  b      3
19 -0.940058  b      2

In [119]:
dfc=df.copy()

In [120]:
dfc

C1 C2  C1bin
0   0.490417  a      3
1   0.304764  a      3
2  -0.925569  a      2
3   0.049322  a      3
4   0.883035  a      4
5  -0.880704  a      2
6  -0.676126  a      2
7  -2.165110  a      1
8   1.256704  a      4
9  -0.735027  a      2
10 -1.829067  b      1
11  1.649436  b      5
12  0.748258  b      4
13 -0.401665  b      2
14  0.237367  b      3
15  0.365278  b      3
16 -1.440535  b      1
17 -1.469205  b      1
18  0.441842  b      3
19 -0.940058  b      2

In [122]:
high_low = []
mean = df["C1"].mean()
for c in df["C1"]:
    if c > mean:
        c = "high"
    else:
        c = "low"
    high_low.append(c)
df["high_low"] = high_low


In [123]:
df

C1 C2  C1bin high_low
0   0.490417  a      3     high
1   0.304764  a      3     high
2  -0.925569  a      2      low
3   0.049322  a      3     high
4   0.883035  a      4     high
5  -0.880704  a      2      low
6  -0.676126  a      2      low
7  -2.165110  a      1      low
8   1.256704  a      4     high
9  -0.735027  a      2      low
10 -1.829067  b      1      low
11  1.649436  b      5     high
12  0.748258  b      4     high
13 -0.401665  b      2      low
14  0.237367  b      3     high
15  0.365278  b      3     high
16 -1.440535  b      1      low
17 -1.469205  b      1      low
18  0.441842  b      3     high
19 -0.940058  b      2      low

In [124]:
df['high_low'] =pd.cut(df.C1, bins=[df.C1.min(), df.C1.mean(), df.C1.max()], labels=['low', 'high'])
df['high_low']


0     high
1     high
2      low
3     high
4     high
5      low
6      low
7      NaN
8     high
9      low
10     low
11    high
12    high
13     low
14    high
15    high
16     low
17     low
18    high
19     low
Name: high_low, dtype: category
Categories (2, object): ['low' < 'high']

In [125]:
df['high_low'] = list(map(lambda x: 'high' if x else 'low',df.C1 > df.C1.mean()))
df


C1 C2  C1bin high_low
0   0.490417  a      3     high
1   0.304764  a      3     high
2  -0.925569  a      2      low
3   0.049322  a      3     high
4   0.883035  a      4     high
5  -0.880704  a      2      low
6  -0.676126  a      2      low
7  -2.165110  a      1      low
8   1.256704  a      4     high
9  -0.735027  a      2      low
10 -1.829067  b      1      low
11  1.649436  b      5     high
12  0.748258  b      4     high
13 -0.401665  b      2      low
14  0.237367  b      3     high
15  0.365278  b      3     high
16 -1.440535  b      1      low
17 -1.469205  b      1      low
18  0.441842  b      3     high
19 -0.940058  b      2      low

In [126]:
df['high_low'] = binarize(df['C1'].values.reshape(-1,1), threshold=df['C1'].mean())
df['high_low'].replace({0.0: 'low', 1.0: 'high'}, inplace=True)


In [127]:
df

C1 C2  C1bin high_low
0   0.490417  a      3     high
1   0.304764  a      3     high
2  -0.925569  a      2      low
3   0.049322  a      3     high
4   0.883035  a      4     high
5  -0.880704  a      2      low
6  -0.676126  a      2      low
7  -2.165110  a      1      low
8   1.256704  a      4     high
9  -0.735027  a      2      low
10 -1.829067  b      1      low
11  1.649436  b      5     high
12  0.748258  b      4     high
13 -0.401665  b      2      low
14  0.237367  b      3     high
15  0.365278  b      3     high
16 -1.440535  b      1      low
17 -1.469205  b      1      low
18  0.441842  b      3     high
19 -0.940058  b      2      low

In [128]:
#np.where(조건,참,거짓)
df['high_low']=np.where(df['C1']>df.C1.mean(),'high', 'low')
df

C1 C2  C1bin high_low
0   0.490417  a      3     high
1   0.304764  a      3     high
2  -0.925569  a      2      low
3   0.049322  a      3     high
4   0.883035  a      4     high
5  -0.880704  a      2      low
6  -0.676126  a      2      low
7  -2.165110  a      1      low
8   1.256704  a      4     high
9  -0.735027  a      2      low
10 -1.829067  b      1      low
11  1.649436  b      5     high
12  0.748258  b      4     high
13 -0.401665  b      2      low
14  0.237367  b      3     high
15  0.365278  b      3     high
16 -1.440535  b      1      low
17 -1.469205  b      1      low
18  0.441842  b      3     high
19 -0.940058  b      2      low

In [130]:
df.groupby('high_low').size()
df.groupby('high_low').mean()

C1  C1bin
high_low                 
high      0.642642    3.5
low      -1.146307    1.6

In [131]:
df.groupby('high_low')['C1'].mean()

high_low
high    0.642642
low    -1.146307
Name: C1, dtype: float64

In [134]:
Q1=np.percentile(df['C1'],25) #1사분위수(25%)
Q3=np.percentile(df['C1'],75) #3사분위수(75%)
# IQR=Q3-Q1
# Q3+IQR*1.5
# Q1-IQR*1.5

In [135]:
df['high_med_low']=np.where(df['C1']<Q1,'low', 
                            np.where(df['C1']<Q3,'med','high'))
df

C1 C2  C1bin high_low high_med_low
0   0.490417  a      3     high         high
1   0.304764  a      3     high          med
2  -0.925569  a      2      low          med
3   0.049322  a      3     high          med
4   0.883035  a      4     high         high
5  -0.880704  a      2      low          med
6  -0.676126  a      2      low          med
7  -2.165110  a      1      low          low
8   1.256704  a      4     high         high
9  -0.735027  a      2      low          med
10 -1.829067  b      1      low          low
11  1.649436  b      5     high         high
12  0.748258  b      4     high         high
13 -0.401665  b      2      low          med
14  0.237367  b      3     high          med
15  0.365278  b      3     high          med
16 -1.440535  b      1      low          low
17 -1.469205  b      1      low          low
18  0.441842  b      3     high          med
19 -0.940058  b      2      low          low

In [137]:
pew=pd.read_csv("data/pew.csv")
pew

religion  <$10k  $10-20k  $20-30k  $30-40k  $40-50k  \
0                  Agnostic     27       34       60       81       76   
1                   Atheist     12       27       37       52       35   
2                  Buddhist     27       21       30       34       33   
3                  Catholic    418      617      732      670      638   
4        Don’t know/refused     15       14       15       11       10   
5          Evangelical Prot    575      869     1064      982      881   
6                     Hindu      1        9        7        9       11   
7   Historically Black Prot    228      244      236      238      197   
8         Jehovah's Witness     20       27       24       24       21   
9                    Jewish     19       19       25       25       30   
10            Mainline Prot    289      495      619      655      651   
11                   Mormon     29       40       48       51       56   
12                   Muslim      6        7        9       10        9   
13                 Orthodox     13       17       23       32       32   
14          Other Christian      9        7       11       13       13   
15             Other Faiths     20       33       40       46       49   
16    Other World Religions      5        2        3        4        2   
17             Unaffiliated    217      299      374      365      341   

    $50-75k  $75-100k  $100-150k  >150k  Don't know/refused  
0       137       122        109     84                  96  
1        70        73         59     74                  76  
2        58        62         39     53                  54  
3      1116       949        792    633                1489  
4        35        21         17     18                 116  
5      1486       949        723    414                1529  
6        34        47         48     54                  37  
7       223       131         81     78                 339  
8        30        15         11      6                  37  
9        95        69         87    151                 162  
10     1107       939        753    634                1328  
11      112        85         49     42                  69  
12       23        16          8      6                  22  
13       47        38         42     46                  73  
14       14        18         14     12                  18  
15       63        46         40     41                  71  
16        7         3          4      4                   8  
17      528       407        321    258                 597

In [138]:
pew.head()

religion  <$10k  $10-20k  $20-30k  $30-40k  $40-50k  $50-75k  \
0            Agnostic     27       34       60       81       76      137   
1             Atheist     12       27       37       52       35       70   
2            Buddhist     27       21       30       34       33       58   
3            Catholic    418      617      732      670      638     1116   
4  Don’t know/refused     15       14       15       11       10       35   

   $75-100k  $100-150k  >150k  Don't know/refused  
0       122        109     84                  96  
1        73         59     74                  76  
2        62         39     53                  54  
3       949        792    633                1489  
4        21         17     18                 116

In [140]:
#데이터 구조 변경 : 피봇테이블, 스택/언스택, 멜트(melt)
data = pd.DataFrame({'c_ID' : ['C_001', 'C_001', 'C_002', 'C_002'],
'p_CD' : ['P_001', 'P_002', 'P_001', 'P_002'],
'p_cnt' : [1, 2, 3, 4],
'p_amt' : [100, 200, 300, 400]})

In [141]:
data

c_ID   p_CD  p_cnt  p_amt
0  C_001  P_001      1    100
1  C_001  P_002      2    200
2  C_002  P_001      3    300
3  C_002  P_002      4    400

In [147]:
help(pd.melt)

Help on function melt in module pandas.core.reshape.melt:

melt(frame: 'DataFrame', id_vars=None, value_vars=None, var_name=None, value_name='value', col_level=None, ignore_index: bool = True) -> 'DataFrame'
    Unpivot a DataFrame from wide to long format, optionally leaving identifiers set.
    
    This function is useful to massage a DataFrame into a format where one
    or more columns are identifier variables (`id_vars`), while all other
    columns, considered measured variables (`value_vars`), are "unpivoted" to
    the row axis, leaving just two non-identifier columns, 'variable' and
    'value'.
    
    Parameters
    ----------
    id_vars : tuple, list, or ndarray, optional
        Column(s) to use as identifier variables.
    value_vars : tuple, list, or ndarray, optional
        Column(s) to unpivot. If not specified, uses all columns that
        are not set as `id_vars`.
    var_name : scalar
        Name to use for the 'variable' column. If None it uses
        ``fram

In [149]:
data

c_ID   p_CD  p_cnt  p_amt
0  C_001  P_001      1    100
1  C_001  P_002      2    200
2  C_002  P_001      3    300
3  C_002  P_002      4    400

In [148]:
pd.melt(data)

variable  value
0      c_ID  C_001
1      c_ID  C_001
2      c_ID  C_002
3      c_ID  C_002
4      p_CD  P_001
5      p_CD  P_002
6      p_CD  P_001
7      p_CD  P_002
8     p_cnt      1
9     p_cnt      2
10    p_cnt      3
11    p_cnt      4
12    p_amt    100
13    p_amt    200
14    p_amt    300
15    p_amt    400

In [150]:
data

c_ID   p_CD  p_cnt  p_amt
0  C_001  P_001      1    100
1  C_001  P_002      2    200
2  C_002  P_001      3    300
3  C_002  P_002      4    400

In [152]:
pd.melt(data, id_vars=['c_ID','p_CD'])

c_ID   p_CD variable  value
0  C_001  P_001    p_cnt      1
1  C_001  P_002    p_cnt      2
2  C_002  P_001    p_cnt      3
3  C_002  P_002    p_cnt      4
4  C_001  P_001    p_amt    100
5  C_001  P_002    p_amt    200
6  C_002  P_001    p_amt    300
7  C_002  P_002    p_amt    400

In [153]:
pd.melt(data, id_vars=['c_ID','p_CD'], var_name='pch_cd', value_name='pch_value')

c_ID   p_CD pch_cd  pch_value
0  C_001  P_001  p_cnt          1
1  C_001  P_002  p_cnt          2
2  C_002  P_001  p_cnt          3
3  C_002  P_002  p_cnt          4
4  C_001  P_001  p_amt        100
5  C_001  P_002  p_amt        200
6  C_002  P_001  p_amt        300
7  C_002  P_002  p_amt        400

In [154]:
data

c_ID   p_CD  p_cnt  p_amt
0  C_001  P_001      1    100
1  C_001  P_002      2    200
2  C_002  P_001      3    300
3  C_002  P_002      4    400

In [156]:
data_melt=pd.melt(data, id_vars=['c_ID', 'p_CD'], 
        var_name='pch_cd', 
        value_name='pch_value')
data_melt
#melt된 데이터는 0번부터 행 index 번호가 부여됨

c_ID   p_CD pch_cd  pch_value
0  C_001  P_001  p_cnt          1
1  C_001  P_002  p_cnt          2
2  C_002  P_001  p_cnt          3
3  C_002  P_002  p_cnt          4
4  C_001  P_001  p_amt        100
5  C_001  P_002  p_amt        200
6  C_002  P_001  p_amt        300
7  C_002  P_002  p_amt        400

In [158]:
data_melt.index
data_melt.columns
#melt된 데이터는 0번부터 행 index 번호가 부여됨

Index(['c_ID', 'p_CD', 'pch_cd', 'pch_value'], dtype='object')

In [159]:
data_melt

c_ID   p_CD pch_cd  pch_value
0  C_001  P_001  p_cnt          1
1  C_001  P_002  p_cnt          2
2  C_002  P_001  p_cnt          3
3  C_002  P_002  p_cnt          4
4  C_001  P_001  p_amt        100
5  C_001  P_002  p_amt        200
6  C_002  P_001  p_amt        300
7  C_002  P_002  p_amt        400

In [162]:
pd.pivot_table(data_melt, index=['c_ID', 'p_CD'], columns='pch_cd', 
               values='pch_value')

pch_cd       p_amt  p_cnt
c_ID  p_CD               
C_001 P_001    100      1
      P_002    200      2
C_002 P_001    300      3
      P_002    400      4

In [164]:
pew.columns

Index(['religion', '<$10k', '$10-20k', '$20-30k', '$30-40k', '$40-50k',
       '$50-75k', '$75-100k', '$100-150k', '>150k', 'Don't know/refused'],
      dtype='object')

In [167]:
np.shape(pew)

(18, 11)

In [ ]:
# pew를 religion income count 3개 열로 재구성

#      religion income count
# ---------------------------------
#     Agnostic   <$10k   27
#     Agnostic   $10-20k 34
#     ...
#     Unaffiliated <$10k   217
#     ...
#     Unaffiliated  $10-20k 597

In [168]:
pew

religion  <$10k  $10-20k  $20-30k  $30-40k  $40-50k  \
0                  Agnostic     27       34       60       81       76   
1                   Atheist     12       27       37       52       35   
2                  Buddhist     27       21       30       34       33   
3                  Catholic    418      617      732      670      638   
4        Don’t know/refused     15       14       15       11       10   
5          Evangelical Prot    575      869     1064      982      881   
6                     Hindu      1        9        7        9       11   
7   Historically Black Prot    228      244      236      238      197   
8         Jehovah's Witness     20       27       24       24       21   
9                    Jewish     19       19       25       25       30   
10            Mainline Prot    289      495      619      655      651   
11                   Mormon     29       40       48       51       56   
12                   Muslim      6        7        9       10        9   
13                 Orthodox     13       17       23       32       32   
14          Other Christian      9        7       11       13       13   
15             Other Faiths     20       33       40       46       49   
16    Other World Religions      5        2        3        4        2   
17             Unaffiliated    217      299      374      365      341   

    $50-75k  $75-100k  $100-150k  >150k  Don't know/refused  
0       137       122        109     84                  96  
1        70        73         59     74                  76  
2        58        62         39     53                  54  
3      1116       949        792    633                1489  
4        35        21         17     18                 116  
5      1486       949        723    414                1529  
6        34        47         48     54                  37  
7       223       131         81     78                 339  
8        30        15         11      6                  37  
9        95        69         87    151                 162  
10     1107       939        753    634                1328  
11      112        85         49     42                  69  
12       23        16          8      6                  22  
13       47        38         42     46                  73  
14       14        18         14     12                  18  
15       63        46         40     41                  71  
16        7         3          4      4                   8  
17      528       407        321    258                 597

In [171]:
pd.melt(pew, id_vars=['religion'], var_name='income', value_name='count')

religion              income  count
0                 Agnostic               <$10k     27
1                  Atheist               <$10k     12
2                 Buddhist               <$10k     27
3                 Catholic               <$10k    418
4       Don’t know/refused               <$10k     15
..                     ...                 ...    ...
175               Orthodox  Don't know/refused     73
176        Other Christian  Don't know/refused     18
177           Other Faiths  Don't know/refused     71
178  Other World Religions  Don't know/refused      8
179           Unaffiliated  Don't know/refused    597

[180 rows x 3 columns]

In [173]:
billboard=pd.read_csv("data/billboard.csv")
billboard

year            artist                    track  time date.entered  wk1  \
0    2000             2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26   87   
1    2000           2Ge+her  The Hardest Part Of ...  3:15   2000-09-02   91   
2    2000      3 Doors Down               Kryptonite  3:53   2000-04-08   81   
3    2000      3 Doors Down                    Loser  4:24   2000-10-21   76   
4    2000          504 Boyz            Wobble Wobble  3:35   2000-04-15   57   
..    ...               ...                      ...   ...          ...  ...   
312  2000       Yankee Grey     Another Nine Minutes  3:10   2000-04-29   86   
313  2000  Yearwood, Trisha          Real Live Woman  3:55   2000-04-01   85   
314  2000   Ying Yang Twins  Whistle While You Tw...  4:19   2000-03-18   95   
315  2000     Zombie Nation            Kernkraft 400  3:30   2000-09-02   99   
316  2000   matchbox twenty                     Bent  4:12   2000-04-29   60   

      wk2   wk3   wk4   wk5  ...  wk67  wk68  wk69  wk70  wk71  wk72  wk73  \
0    82.0  72.0  77.0  87.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
1    87.0  92.0   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
2    70.0  68.0  67.0  66.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
3    76.0  72.0  69.0  67.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
4    34.0  25.0  17.0  17.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
..    ...   ...   ...   ...  ...   ...   ...   ...   ...   ...   ...   ...   
312  83.0  77.0  74.0  83.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
313  83.0  83.0  82.0  81.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
314  94.0  91.0  85.0  84.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
315  99.0   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
316  37.0  29.0  24.0  22.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   

     wk74  wk75  wk76  
0     NaN   NaN   NaN  
1     NaN   NaN   NaN  
2     NaN   NaN   NaN  
3     NaN   NaN   NaN  
4     NaN   NaN   NaN  
..    ...   ...   ...  
312   NaN   NaN   NaN  
313   NaN   NaN   NaN  
314   NaN   NaN   NaN  
315   NaN   NaN   NaN  
316   NaN   NaN   NaN  

[317 rows x 81 columns]

In [174]:
pd.melt(billboard, 
        id_vars=['year','artist', 'track', 'time', 'date.entered'], 
        var_name='week', value_name='rating')


year            artist                    track  time date.entered  \
0      2000             2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26   
1      2000           2Ge+her  The Hardest Part Of ...  3:15   2000-09-02   
2      2000      3 Doors Down               Kryptonite  3:53   2000-04-08   
3      2000      3 Doors Down                    Loser  4:24   2000-10-21   
4      2000          504 Boyz            Wobble Wobble  3:35   2000-04-15   
...     ...               ...                      ...   ...          ...   
24087  2000       Yankee Grey     Another Nine Minutes  3:10   2000-04-29   
24088  2000  Yearwood, Trisha          Real Live Woman  3:55   2000-04-01   
24089  2000   Ying Yang Twins  Whistle While You Tw...  4:19   2000-03-18   
24090  2000     Zombie Nation            Kernkraft 400  3:30   2000-09-02   
24091  2000   matchbox twenty                     Bent  4:12   2000-04-29   

       week  rating  
0       wk1    87.0  
1       wk1    91.0  
2       wk1    81.0  
3       wk1    76.0  
4       wk1    57.0  
...     ...     ...  
24087  wk76     NaN  
24088  wk76     NaN  
24089  wk76     NaN  
24090  wk76     NaN  
24091  wk76     NaN  

[24092 rows x 7 columns]